### ISSUE TITLE
Allow the PWD to contain a configuration file that can act as another layer.

### ISSUE THREAD

**Issue by RandomNoun7** [PoshCode/Configuration#23]
It would be nice if you clone a project's git repository, and the repository could contain a configuration file for something like a test framework module, that could override specific machine wide settings that may need to be tweaked on a case by case basis. 

Doing this at the user level could be difficult because not only would the user need to know which tweaks need to be made to specific projects, something contributors may not know easily, but a settings schema for the module would need to be able to understand which project you are working on and how to jigger the settings for specific modules.

I am willing to help with a PR on this, but I am creating this issue to start the discussion on whether you think this would be a useful capability.

I would like to use this module as the settings manager for a module I am working on, but being able to specify settings overrides that live in the project repository is a high priority objective for me.

Thanks,
Bill

**Comment by scrthq** [comment]
Doesn't Configuration already look in the module folder for a Configuration file to use as its base (or only configuration file, if that's all that's present on the machine)?

https://github.com/PoshCode/Configuration/blob/master/Source/Configuration.psm1#L388..L394

**Comment by RandomNoun7** [comment]
Yes it does. What I'm proposing is a layer that lives with a code bases git repository that can override specific settings from that higher level module layer.

**Comment by RandomNoun7** [comment]
Yeah I think so. To me the current working directory represents the tightest possible scope in which to place a preference setting. It should represent the scope at which preferences are most strongly preferred.

Lets say I have a module that runs tests for users. One of the settings that needs to be saved is a setting I'll call `platformVersion` and it specifies the version of the software under test should be installed in runner hosts. 

For 90% of test runs for modules that run against that platform, you can simply use latest, and so that is the setting I ship with the module.

But one module has a known bug that isn't planned to be fixed for some time, and so it's test runs need to be pinned to latest -1. I would like to include a settings file in the modules git repo that overrides the module scoped setting so that the knowledge of where that version needs to be pinned lives with the repository. When the bug is fixed I can remove the setting from the repo scoped settings file, and all collaborators on the project automatically get the update when they fetch latest from the repo.

If I understand your explanation of the rules of how things currently work, I as the maintainer of that module project am unable to ensure all collaborators receive the override without contacting them manually and warning them that they have to do this on their own. If I include a settings file in the repository it will just get overridden by the machine scoped setting. Worse, if they run tests both on this module and ones that do not need this override, they need to just remember on their own that this switch has to be made each time they start work on a different module and then switch back to working on this one.

**Comment by RandomNoun7** [comment]
You know, having re read what you wrote, I think all I probably want is a layer 5 that would represent the current working directory. 

So if I clone a git repo at c:\src\myrepo and cd into that directory, then the layer 5 I have in mind would now be a settings file in that directory which would overlay the others.

**Comment by RandomNoun7** [comment]
I see the edit you made. I think that probably solves the issue for me. I can just code my PowerShell modules settings cmdlets to always check for a settings file in `$PWD` and import it if it's present. I admit that I think a case can be made that this should be a default behavior for this module so that I as the author of my module don't have to do that, and if you agree I wouldn't mind attempting a PR to do that. But if not that's ok, I can code the work around into my own modules.

Thanks for taking the time to reply.

**Comment by Jaykul** [comment]
Yeah, I think it's simple enough to implement it for your use case, but I don't think that I want the _current_ system to get overridden by the local folder -- the current config files are based on the  way normal Windows apps work, and if a local file could override things _for all the current users_, it might feel like you're being hijacked. 

_Also,_ the current implementation is completely based on "MyModuleA" folders in two or three specific locations with a file that's specifically named "Configuration.psd1" -- so adding an override in the current folder would mean a new naming scheme (which would probably break the feature I proposed in #24 because that requires the user to specify the name of the config file)...

## What about an alternative:

I have been thinking about a completely separate layer system based on the way tools like `git` and other source control tools, for instance, use config stored within the current folder _and it's ancestors_, with the exception of a global config that's usually stored in `~\` (the user's OS profile folder).

So the idea would be to make a `pwd` based system where for "MyModuleA" we would look for a `.MyModuleA` file (or folder?) in `pwd` and traverse the path looking for lower layers in each folder down to the root. Possibly stopping at `~\` if you hit that first, because once you hit global, you can't keep going down, right?

Would that suit you better?

**Comment by RandomNoun7** [comment]
RE: Alternative PWD based config. Overall I like it, and the module named .config file functionality is what I'm looking for out of a PWD config file. It seems a downside would likely be the loss of settings that follow you around in your roaming profile. Another question would be how far up would you go looking for ancestors? Would you always go from PWD all the way up to c:\ or whatever drive letter you're on? To me another possible analogue to look to for how this could work would be the way .NET and IIS do configuration inheritance where you have a machine.config/applicationhost.config and then web.config files starting at a certain path. I will just admit that I haven't incorporated the settings module into one my project yet so I don't know the current behavior well enough to really have a useful opinion for you on how things like `Set-Configuration` and `Export-Configuration` should work in that kind of environment.

I don't think for my own uses though that a whole new scheme is really necessary. As you pointed out I can just code my own module to look for a module named settings file in PWD and handle that myself. I just don't agree that getting settings automatically imported from PWD on top of your existing layers would feel like being hijacked. A file in PWD is the most clearly visible and easily overrideable place to get a setting from. If you don't like the setting that came in from the repo's dot file, just delete it. Ideally put in a PR explaining why a certain setting in the repo doesn't make sense for all contributors to the project.

**Comment by Jaykul** [comment]
Hijacking ....

Well, imagine you're using a [PowerLine](/jaykul/powerline) prompt, and then you `cd` into a source-control folder and instead of your own custom prompt it runs **whatever code the repository author wants**.  

If that was a possibility, PowerLine would need to disable it **completely** in order to be safe.  And yes, PowerLine may be relatively unique in that it's actually storing executable scriptblocks in the configuration, but it's certainly not unique in the fact that the configuration it's storing is personal preferences of users, who will **not** want those preferences changed just because they're working on someone else's project...

Lacking any data, it's obviously just a gut feeling -- but I think that the majority of modules would **not** want configuration overrides based on the current working directory. 

I mean, look at software in general: the proportion of software that supports overriding configuration with local working-directory config files is vanishingly small (it's just a small fraction of software development tools -- I can't even think of any system administration or forensics or security tools that behave like that, nor any general-purpose software)...

**Comment by RandomNoun7** [comment]
The module I'm writing is a development tool, which may be where this disconnect is coming from I guess. As to your PowerLine example, if I clone a repo with bad PowerLine settings as a dot file in it, yeah that would be weird. Why would someone do that? I would file an issue with the project maintainers to get the file removed. For my use case though, the ability for a project to know it's own appropriate settings is what I need. Just like each repo needs its own appveyor.yml or gitlab.yml.

**Comment by RandomNoun7** [comment]
Also, it's worth noting that the ability to have a totally different powerline prompt in different folders, depending on the folder you're in sounds really cool. If a project did that to me, yeah that would be annoying if they abused it, but as a feature, it sounds cool.

**Comment by Jaykul** [comment]
For what it's worth ... I finally (all these years later) shipped the first draft of the file-tree based configuration as `Import-ParameterConfiguration` which is described in [DefaultParameters.feature](https://github.com/PoshCode/Configuration/blob/4c26fdae16a7e4d3b23c7403b0f93d1944cdc575/Specs/DefaultParameters.feature).

I will document it better later, but basically it looks in the current folder and parent folders for a configuration file. By default, it's a _per-command_ way to load _default parameter values_ from a file in the current folder (tree).

**Comment by RandomNoun7** [comment]
Hilariously I'm only now seeing the email notification about this thread as I go on a crusade to clean out my email inbox. Congrats to you and your users on finally getting this done.
