### ISSUE TITLE
Question: Latest published version not on Powershell gallery

### ISSUE THREAD

**Issue by mi-hol** [PoshCode/Configuration#35]
I wonder if it's intentional that 1.3.1 is the latest version on Powershell gallery.
Any reason?

**Comment by mi-hol** [comment]
@Jaykul as no reply was posted within 3 months I wonder if this repo is still actively maintained

**Comment by Jaykul** [comment]
Sorry, I have too many projects, so I sort of go around updating them one at a time, and I'm not very good at github notifications.

It _is_ intentional that 1.3.1 is the last version on the gallery. 

There is a _pre-release_ of 1.4.0 available, but the intermediary builds of 1.3.x weren't worth publishing (they were basically artifacts of my struggles with CI builds).
